logging:
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:sqlserver://161.97.75.101:1433;databaseName=iMenu
    username: user
    password: Pa$$w0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    tomcat:
      test-while-idle: true
      validation-query: SELECT getDate()
    initialization-mode: never
    platform: mssql
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: false
        use_sql_comments : false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql : false
server:
  port: 8080
